### ISSUE TITLE
Calendar Widget 

### ISSUE THREAD

**Issue by SyamBabu-M** [culturecreates/footlight-calendar-widget#28]
```[tasklist]
### Tasks
- [x] Add Versioning to widget.
- [x] Currently parameter values passed to src of iframe is percent encoded twice. It should be encoded once only.
- [x] Implement way to fetch eventSearchURl and eventUrl from the widget itself. Currently both are passed as search params.
- [x] Change the domain of widget to footlight.io
```

Discussion [document](https://docs.google.com/document/d/1I7sKHZEYNgOd2FJgDhTXysqNmA4K2f3fUHL9OZDfWlI/edit)

**Comment by troughc** [comment]
@SyamBabu-M should I add the tag "bug" to this? And would it be more efficient for you to tackle this issue around the same time as https://github.com/culturecreates/footlight-app/issues/1036 ? (or just after)?

**Comment by SyamBabu-M** [comment]
@troughc I think it's better to add an enhancement tag as only the last task can be considered a bug. Except last task all other tasks are very different from [https://github.com/culturecreates/footlight-app/issues/1036](1036), so I think it is better to do this separately.

**Comment by saumier** [comment]
@SyamBabu-M I have taken a look at your idea of using the Open API to obtain the template URLs instead of passing the template URLs to the widget itself.   

As a reminder, there are the concern raised by Caitlin in the [original design doc](https://docs.google.com/document/d/1I7sKHZEYNgOd2FJgDhTXysqNmA4K2f3fUHL9OZDfWlI/edit#heading=h.36gwury9xg50)
> @[gregory@culturecreates.com](mailto:gregory@culturecreates.com) I've been thinking about this again. A concern with this approach: if the web agency changes the template URL that uses placeholders, the widget will break (links won't work). Nobody will know unless someone tries the widget.
So: could we not implement have some kind of check to ensure the links are always working? Maybe a 'handshake' with the web agency that is responsible for the site? Maybe add a safeguard (send a bot to pull the data from the frontend website and test that it's working, something like that?)
If we do this, the customer would no longer risk having their widgets fail without anyone being aware (until someone checks the actual calendar widget). And if we do this, we don't need to get the info through the CMS anymore right? We would 'know'. 
Let's discuss. cc @[syam@culturecreates.com](mailto:syam@culturecreates.com) @[suhail@culturecreates.com](mailto:suhail@culturecreates.com)

To address the concern that nobody sees if the template URLs are broken, we can discuss the following:
1.  add a button in CMS to "view event" on customer website. This shortcut will get used by users of CMS and therefore increase awareness of any problem.
2. Monitor the URL template with Datadog, and if it breaks (404) then trigger an alarm.

When I think of the widget I have the following idea: have the widget always call back CMS which then redirects the browser to the customer website using the URL template.  

This has the some advantages: 
1. Widget does not need to make an extra API call to Open API to get the template URLs upon loading the widget.
2. We can begin to measure how much traffic the widget is driving to websites (similar to the way Google search results always redirect via Google when you click on a search result link)



@SyamBabu-M @sahalali  I'd like to know your feedback on this idea.

**Comment by SyamBabu-M** [comment]
@saumier I really like this idea 

Just to confirm my understanding: we'll be redirecting to a page in the CMS, then use the open API to fetch the widget template URLs and route them to the customer websites from there.
Did I get that right?

**Comment by SyamBabu-M** [comment]
@saumier please take a look into this [comment](https://docs.google.com/document/d/1I7sKHZEYNgOd2FJgDhTXysqNmA4K2f3fUHL9OZDfWlI/edit?disco=AAABL_LbkBk)

**Comment by saumier** [comment]
@SyamBabu-M I added my comments in the doc. Let me know what you think and if you can continue working on the design.

**Comment by saumier** [comment]
@sahalali @SyamBabu-M Please review the design proposal and leave your comments.

**Comment by sahalali** [comment]
Added an API to the admin-api [see the API here](https://staging.api.cms.footlight.io/api/#/Miscellaneous%20APIs/MiscellaneousController_getCustomerCalendarRedirectionURL)


Example:
https://staging.api.cms.footlight.io/api/#/Miscellaneous%20APIs/MiscellaneousController_getCustomerCalendarRedirectionURL


This API will redirect to the customer's website.

**Comment by sahalali** [comment]
The new API is moved to open-api.
Please note the URL below:
https://staging.api.footlight.io/api/#/Miscellaneous%20APIs/MiscellaneousController_getCustomerCalendarRedirectionURL

**Comment by troughc** [comment]
Tested both Signe Laval and Tout Culture widgets on chrome in staging : PASSED
tested see all events with and without applying (date and keyword) filtering:passed 
tested changing the language: passed 
tested links that go directly to events  in both languages for tout culture: passed

Looks good! Assigning back to you @SyamBabu-M as this is good to go.

**Comment by troughc** [comment]
@SyamBabu-M @saumier @sahalali in the interest of not holding up the development process, Gregory and I had a quick discussion on how the 'See all events' button in the widget should work. 
the question was: should the button carry over filters applied in the widget or should the button just show 'all events' on the listing page at the destination site (with no filters like date or search terms carried over)?

The conclusion Gregory and I agreed to is to NOT carry over any filtering - just go to the main listing page with all events displayed. In other words, keep it very generic. I believe that this is what a user would expect. 
So I would say that button functions correctly as it is designed right now, today. 

Please let me know if you have questions.

**Comment by SyamBabu-M** [comment]
@sahalali the only task left is to change the domain name of the widget. Please look into this.

**Comment by saumier** [comment]
@troughc Should tab in the CMS Settings screen say "CMS Widget" to be consistent with our Footlight CMS name, or do you want to keep "Calendar Widget"?  Your answer will determine which domain we use for the widget url: cms-widget.footlight.io or calendar-widget.footlight.io.  I prefer cms-widget because it is more consistent with our product name and the url cms.footlight.io which the customer knows. And in the future if we use the widget to list a directory of organizations or artists then it will still work. As soon as you answer I will create the domain in our DNS so Syam can compete the last task. Thx.

**Comment by saumier** [comment]
@SyamBabu-M @sahalali @dev-aravind Following our conversation this morning, I made a little sequence diagram to show the CORS error. Let me know if it makes sense.

![Image](https://github.com/culturecreates/footlight-calendar-widget/assets/419491/6699e0f3-b1a3-4529-87cd-97f92d91eb48)

**Comment by SyamBabu-M** [comment]
> [@SyamBabu-M](https://github.com/SyamBabu-M) [@sahalali](https://github.com/sahalali) [@dev-aravind](https://github.com/dev-aravind) Following our conversation this morning, I made a little sequence diagram to show the CORS error. Let me know if it makes sense.
> 
> ![Image](https://private-user-images.githubusercontent.com/419491/334836405-ae1e0356-25e2-4796-927d-dd6d32f3afc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzA4NjEsIm5iZiI6MTcxNzA3MDU2MSwicGF0aCI6Ii80MTk0OTEvMzM0ODM2NDA1LWFlMWUwMzU2LTI1ZTItNDc5Ni05MjdkLWRkNmQzMmYzYWZjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQxMjAyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWIzODk3YTE0YmJhM2UwYzQ3MGEwNGFiMmIwYjBhOGJkMDFmM2Q1MTkwYjRlNjJlMTM5MTkzZTg1ZDdiMjI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uSchKLH8NwkfRjaciSaBAFALvnP_xt1LzSyc9uKppaY)
> 
> Here the browser is making the request, not the web app running in the browser.
> 
> ![Image](https://private-user-images.githubusercontent.com/419491/334836441-a9c1e83c-6a9a-4eda-bb78-05778fe3ad84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzA4NjEsIm5iZiI6MTcxNzA3MDU2MSwicGF0aCI6Ii80MTk0OTEvMzM0ODM2NDQxLWE5YzFlODNjLTZhOWEtNGVkYS1iYjc4LTA1Nzc4ZmUzYWQ4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQxMjAyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGIxYTNhNDZhMzEzZjc2NTU5Mzg0Mjg1NDg3Mzk1NzBmYjIwYWFmOTFjODY3Nzk1MTdiNDQ5NGIyYWU2NTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o3rGc-rnmE06Eq6XkBD-BugwV_5v5942y6r2KwpVpL4)

this makes sense.

**Comment by saumier** [comment]
@SyamBabu-M Now that Caitlin has decided to call it the listing widget I will create a domain [listing-widget.footlight.io](http://listing-widget.footlight.io/) so Syam can update the widget code.

**Comment by saumier** [comment]
@SyamBabu-M I have created https://listing-widget.footlight.io which redirects to a cloudFront distribution with the source S3 bucket called cms-widget.footlight.io.s3-website.ca-central-1.amazonaws.com.

Let me know if you need anything else to complete changing the domain of the widget in the share widget screen. It should be changed from <iframe src="https://s3.ca-central-1.am...  to <iframe src="https://listing-widget.footlight.io...

**Comment by SyamBabu-M** [comment]
@saumier What is the domain of the staging widget?

**Comment by saumier** [comment]
@SyamBabu-M This is not working for me. In the AmplifyApp https://pr-1132.dla06mbe0wyl7.amplifyapp.com/

The link still has the eventUrl param, and the searchEventsUrl param.  

` <iframe src="https://s3.ca-central-1.amazonaws.com/staging.cms-widget.footlight.io/index.html?eventUrl=https%3A%2F%2Ftoutculture.ca%2F%24%7Blocale%7D%2Fevent-detail%2F%3Fevent%3D%24%7BeventId%7D&searchEventsUrl=https%3A%2F%2Ftoutculture.ca%2F%24%7Blocale%7D%2Ffilter-evenements%2F&logo=https%3A%2F%2Fstaging.images.footlight.io%2Fiiif%2F3%2Fa6182b2e-85fa-4ad9-be05-56c9e966c498.png%2Ffull%2Fmax%2F0%2Fdefault.png&locale=en&limit=9&color=%23607EFC&calendar=tout-culture&calendarName=Tout+culture&height=600" width="100%" style="max-width:1000px; border:none" height="600px"></iframe>`

**Comment by SyamBabu-M** [comment]
@saumier I have removed the template url from iframe code.
@sahalali the content negotiation API is redirecting to the event listing page instead of the event details page of the client site. This is happening for DICI.ca calendar only.

**Comment by SyamBabu-M** [comment]
> [@SyamBabu-M](https://github.com/SyamBabu-M) This is not working for me. In the AmplifyApp https://pr-1132.dla06mbe0wyl7.amplifyapp.com/
> 
> 1. Links to events from the widget to culture-mauricie (dici) are not working.
> 2. The wdiget code to copy still has the eventUrl param, and the searchEventsUrl param. These should be removed.
> 
> ` <iframe src="https://s3.ca-central-1.amazonaws.com/staging.cms-widget.footlight.io/index.html?eventUrl=https%3A%2F%2Ftoutculture.ca%2F%24%7Blocale%7D%2Fevent-detail%2F%3Fevent%3D%24%7BeventId%7D&searchEventsUrl=https%3A%2F%2Ftoutculture.ca%2F%24%7Blocale%7D%2Ffilter-evenements%2F&logo=https%3A%2F%2Fstaging.images.footlight.io%2Fiiif%2F3%2Fa6182b2e-85fa-4ad9-be05-56c9e966c498.png%2Ffull%2Fmax%2F0%2Fdefault.png&locale=en&limit=9&color=%23607EFC&calendar=tout-culture&calendarName=Tout+culture&height=600" width="100%" style="max-width:1000px; border:none" height="600px"></iframe>`

I have not added the staging domain to the code yet. The PR testing links run the staging environment so the change will not be visible there.

**Comment by sahalali** [comment]
@SyamBabu-M Please remember below are the widget settings for DICI.ca calendar. 

"widgetSettings": {
    "listEventsUrlTemplate": "https://dici.ca/evenements",
    "eventDetailsUrlTemplate": "https://dici.ca/evenements/${eventName}"
  },
  
Currently, the content negotiation API does not support event-slug. If we intend to support event-slug, we must first ensure its uniqueness. Currently, the slug does not undergo a uniqueness check.

The Event name in the template should be event-slug not the name. I see the same in the signe-laval config as well.

cc @saumier

**Comment by saumier** [comment]
@sahalali I think this is live. If everything is done and pushed to production please close this issue.
